package com.bachelorthesis.beekeeperMobile.intentRecognizer

/**
 * A data class to hold the structured output from the intent recognizer.
 *
 * @param intentName The name of the recognized intent (e.g., "create_log").
 * @param entities A map of extracted entities (e.g., "hive_id" to "12").
 * @param responseText An optional, natural language response generated by the recognizer.
 */
data class StructuredIntent(
    val intentName: String,
    val entities: Map<String, String> = emptyMap(),
    val responseText: String? = null // NEW: Field for LLM-generated response
) {
    companion object {
        // A singleton instance for unknown or failed recognitions.
        // The response text is now handled by the LLM's prompt.
        val UNKNOWN = StructuredIntent("unknown")
    }
}