# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # This first job is new. It runs on every push and determines which parts of the repo have changed.
  filter-paths:
    name: Determine Changed Paths
    runs-on: ubuntu-latest
    # We need to output the results of the filter so other jobs can use them
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      android: ${{ steps.filter.outputs.android }}
      workflow: ${{ steps.filter.outputs.workflow }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Path Filter
        uses: dorny/paths-filter@v3
        id: filter # Give the step an ID so we can refer to its outputs
        with:
          filters: |
            backend:
              - 'apps/beekeeperBackend/**'
            android:
              - 'apps/beekeeperMobile/**'
            workflow:
              - '.github/workflows/**'

  # The backend job now depends on the filter job
  backend-ci:
    name: Backend CI
    runs-on: ubuntu-latest
    needs: filter-paths # This job will not start until 'filter-paths' is complete
    # The 'if' condition is now much simpler and more reliable
    if: needs.filter-paths.outputs.backend == 'true' || needs.filter-paths.outputs.workflow == 'true'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Vet, Test, and Build Backend
        run: |
          go vet ./...
          go test -v ./...
          go build -o beekeeper-backend
        working-directory: ./apps/beekeeperBackend

  # The android job also depends on the filter job
  android-ci:
    name: Android CI
    runs-on: ubuntu-latest
    needs: filter-paths
    if: needs.filter-paths.outputs.android == 'true' || needs.filter-paths.outputs.workflow == 'true'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'jetbrains'

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: ./apps/beekeeperMobile

      - name: Lint and Test Android App
        # We use 'test' which automatically runs lint and all local unit tests.
        run: ./gradlew test
        working-directory: ./apps/beekeeperMobile